server:
  port: 6001
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka3000.com:3000/eureka,http://eureka3001.com:3001/eureka,http://eureka3002.com:3002/eureka
  instance:
    instance-id: power-1
    prefer-ip-address: true
    leaseRenewalIntervalSeconds: 10
    leaseExpirationDurationInSeconds: 30
spring:
  application:
    name: client-power
#  zipkin:
#    baseUrl: http://localhost:9020
#  sleuth:
#    sampler:
#      probability: 1.0 # request采样的数量 默认是0.1也就是10%